export const ADD_CARD = 'ADD_CARD';
export const DELETE_CARD = 'DELETE_CARD';
export const UPDATE_CARD = 'UPDATE_CARD';
export const EDIT_CARD = 'EDIT_CARD';
export const CHANGE_VALUE_NEW_TODO = 'CHANGE_VALUE_NEW_TODO';
export const MOVE_TO_FINISHED_JOB = 'MOVE_TO_FINISHED_JOB';
export const MOVE_TO_TODOLISTS = 'MOVE_TO_TODOLISTS';
